// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import EditorController from "./editor_controller"
import ArticlesFilterController from './articles_filter_controller';

application.register("editor", EditorController)
application.register("articles_filter", ArticlesFilterController)
