version = 1

[[analyzers]]
name = "secrets"
enabled = true

[[analyzers]]
name = "shell"
enabled = true

[[analyzers]]
name = "ruby"
enabled = true
test_patterns = [
  "test/**"
]

[[analyzers]]
name = "docker"
enabled = true
