version: "3"

services:
  goose:
    build: .
    ports:
      - "3000:3000"
    environment:
      SECRET_KEY_BASE: "secret"
      RAILS_LOG_TO_STDOUT: "1"
    volumes:
      - ./docker-compose:/usr/src/goose/data
